kafkaPool: nav-dev
environment: dev
replicas_min: 1
replicas_max: 2
cpu: 100m
memory: 512Mi
db_tier: db-f1-micro
db_diskSize: 10
db_highAvailability: false
db_pointInTimeRecovery: false
env:
  SPRING_PROFILES_ACTIVE: default
