apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykepengesoknad-sak-status-metrikk
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  strategy:
    type: Recreate
  replicas:
    min: {{replicas_min}}
    max: {{replicas_max}}
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health
  readiness:
    path: /internal/health
  startup:
    path: /internal/health
    initialDelay: 40
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: {{memory}}
    requests:
      cpu: {{cpu}}
      memory: {{memory}}
  kafka:
    pool: {{kafkaPool}}
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: {{db_tier}}
        diskType: SSD
        highAvailability: true
        diskSize: {{db_diskSize}}
        pointInTimeRecovery: false
        diskAutoresize: true
        databases:
          - name: sykepengesoknad-sak-status-metrikk-db
            users:
              - name: bigquery-dataprodukt
              - name: bigquery-datastream
            envVarPrefix: DATABASE
        maintenance:
          day: 2
          hour: 2
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
  env:
  {{#each env}}
     - name: {{@key}}
       value: {{this}}
  {{/each}}
