kafkaPool: nav-prod
environment: prod
replicas_min: 1
replicas_max: 6
cpu: 200m
memory: 660Mi
db_tier: db-custom-1-3840
db_diskSize: 100
db_highAvailability: true
db_pointInTimeRecovery: true
env:
  SPRING_PROFILES_ACTIVE: default
